name: "tests are"
on:
  pull_request:
  push:
  workflow_run:
    workflows: ["update flakes"]
    types: [completed]
    branches: [main]

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # dont' use runner since check won't run if it fails.
    - uses: cachix/install-nix-action@v18
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes

    - run: |
        sudo systemctl enable nix-daemon.service
        sudo systemctl start nix-daemon.service
        systemctl status nix-daemon.service
        echo -en "$(jq -r 'del(.nodes.root.inputs.sensitive) | del(.nodes.sensitive)' flake.lock)" > flake.lock
        echo -en "$(jq -r 'del(.nodes.root.inputs."dots-manager") | del(.nodes."dots-manager")' flake.lock)" > flake.lock
        nix flake check .
